spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-195-141-170.eu-west-1.compute.amazonaws.com:5432/dc138t0pvcvmvv
    username: ngdcxakprmgfom
    password: e16c9038bf270c5b8546946d8420bc212cced20cb6109489403834847e67af0a

server:
  port: 8088